version: '2'
services:
    hrninja-app:
        image: hrninja
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://hrninja-postgresql:5432/hrninja
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hrninja-postgresql:
        extends:
            file: postgresql.yml
            service: hrninja-postgresql
